// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Useful for verifying MCP connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-applied-rules.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var appliedRules = [
  { id: "r_001", name: "Pause high-ACoS keywords", status: "running", campaigns: 12, lastRun: "2026-07-05" },
  { id: "r_002", name: "Increase bid on low-ACoS SKUs", status: "running", campaigns: 8, lastRun: "2026-07-05" },
  { id: "r_003", name: "Weekend budget boost", status: "paused", campaigns: 4, lastRun: "2026-06-28" },
  { id: "r_004", name: "Harvest converting search terms", status: "draft", campaigns: 0, lastRun: null },
  { id: "r_005", name: "Q1 holiday launch bids", status: "ended", campaigns: 6, lastRun: "2026-01-05" }
];
var list_applied_rules_default = defineTool2({
  name: "list_applied_rules",
  title: "List applied rules",
  description: "List Anarix advertising automation rules, optionally filtered by status (running, paused, draft, ended).",
  inputSchema: {
    status: z2.enum(["running", "paused", "draft", "ended"]).optional().describe("Optional status filter. Omit to return all rules.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status }) => {
    const rows = status ? appliedRules.filter((r) => r.status === status) : appliedRules;
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { rules: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/get-account-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
var marketplaces = ["amazon-us", "amazon-uk", "walmart-us"];
var get_account_summary_default = defineTool3({
  name: "get_account_summary",
  title: "Get account summary",
  description: "Return a headline performance summary (spend, sales, ACoS, TACoS) for a marketplace over a lookback window.",
  inputSchema: {
    marketplace: z3.enum(marketplaces).describe("Marketplace identifier."),
    lookbackDays: z3.number().int().describe("Lookback window in days (e.g. 7, 30, 90). Clamped to 1-90 in code.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ marketplace, lookbackDays }) => {
    const days = Math.min(90, Math.max(1, Math.floor(lookbackDays)));
    const seed = marketplace.length + days;
    const spend = 1250 * days + seed * 17;
    const sales = spend * 4.2;
    const summary = {
      marketplace,
      lookbackDays: days,
      spend: Number(spend.toFixed(2)),
      sales: Number(sales.toFixed(2)),
      acos: Number((spend / sales * 100).toFixed(2)),
      tacos: Number((spend / (sales * 3.1) * 100).toFixed(2)),
      orders: Math.round(sales / 42)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "anarix-mcp",
  title: "Anarix MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the Anarix advertising intelligence platform. Use `list_applied_rules` to inspect automation rules, `get_account_summary` for headline marketplace KPIs, and `echo` to verify connectivity.",
  tools: [echo_default, list_applied_rules_default, get_account_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
